---
title: "A Wrapper of knitr::include_graphics"
author: "Yongfu Liao"
date: "`r Sys.Date()`"
urlcolor: blue
linkcolor: red
output:
  pdf_document:
    latex_engine: xelatex
  rmarkdown::html_vignette: null
subtitle: Dealing with URL and Invalid File Type Inputs
vignette: |
  %\VignetteIndexEntry{Vignette Title} %\VignetteEncoding{UTF-8} %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = '30%'
)
```

```{r}
library(linguisticsdown)
```


## Passing URL to `path`

```{r}
png_url <- 'https://commonmark.org/images/markdown-mark.png'
gif_url <- 'https://media.giphy.com/media/k3dcUPvxuNpK/giphy.gif'
```

### PNG
```{r}
include_graphics2(png_url)
```

### GIF **without** `alt_path`
```{r}
include_graphics2(gif_url)
```

### GIF with `alt_path`

```{r}
include_graphics2(gif_url, png_url)
```


## Passing Local Figures to `path`

### JPG
```{r}
include_graphics2('Darwin.jpg')
```

### Local GIF **without** `alt_path`
```{r}
include_graphics2('local.gif')
```

### Local GIF with `alt_path`
```{r}
include_graphics2('local.gif', 'local_gif_static.png')
```

`r if (knitr::is_latex_output()) paste0('<!--')`

## PDF Output of this Vignette

<embed src="include_graphics_wrapper.pdf" type="application/pdf" width="90%" height="420px">

`r if (knitr::is_latex_output()) paste0('-->')`


`r if (knitr::is_html_output()) paste0('<!--')`

## HTML Output of this Vignette

See the corresponding HTML output of this vignette at <http://bit.ly/include_graphics2>.

`r if (knitr::is_html_output()) paste0('-->')`
